### GET all persons
GET http://localhost:3001/api/persons

### GET single person
GET http://localhost:3001/api/persons/1

### GET invalid person
GET http://localhost:3001/api/persons/1000

### DELETE single person
DELETE http://localhost:3001/api/persons/1

### DELETE invalid person
DELETE http://localhost:3001/api/persons/1000

### ADD person
POST http://localhost:3001/api/persons

{
    "name": "Lisa Potato",
    "number": "34-21-432542"
}

### ADD invalid person
POST http://localhost:3001/api/persons

{
    "malicious": "malicious thing"
}

### ADD empty person
POST http://localhost:3001/api/persons

{
    
}