### GET all persons
GET http://localhost:3001/api/persons

### GET single person
GET http://localhost:3001/api/persons/1

### GET invalid person
GET http://localhost:3001/api/persons/1000

### DELETE single person
DELETE http://localhost:3001/api/persons/1

### DELETE invalid person
DELETE http://localhost:3001/api/persons/1000

### POST person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Lisa Potato",
    "number": "34-21-432542"
}

### POST invalid person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "malicious": "malicious thing"
}

### POST partially complete person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "1232152"
}

### POST existing person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Lisa Potato"
}

### POST empty person
POST http://localhost:3001/api/persons
Content-Type: application/json

{

}